-*- coding: utf-8-with-signature-unix; -*-

* TODO Is there a better way to implement "mbfl_variable_alloc()" in "src/modules/variables.bash"?
* TODO Libraries infrastructure
** TODO Implement some form of library versioning.

   One way of doing it would be to have file names like:

     libmbfl-git-3.0.0.bash

   that is with a pattern like:

     LIBNAME-SEMVER.bash

   where LIBNAME has  the form "libmbfl-STEM" and  SEMVER is a full  semantic version specification,
   without the leading "v".

** TODO Implement some form of library inspection facility.

   One way of doing it would be to have the preprocessed file start with a line like:

     MBFL_LIBRARY_SPEC=([NAME]="libmbfl-git" [SEMVER]="3.0.0" ...)

   the single first line can be easily extracted from the file and parsed like an associative array.

* TODO Library libmbfl-git
** TODO Interface more commands.
* TODO Library libmbfl-utils
** TODO Overhaul the implementation of file/directory installation/normalisation.
** TODO Redocument the library.
* Local Variables

#+STARTUP: fold

# Local Variables:
# ispell-local-dictionary: "en_GB-ise-w_accents"
# fill-column: 100
# End:
